```{r}
library(shiny) 
library(shinydashboard)
library(DT)

library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)
library(glue)

# Read the data
ecom <- read.csv("Sample - Superstore.csv", stringsAsFactors = T)

#----Correct wrong data types----
ecom <- mutate(
  ecom,
  Order.Date = mdy(Order.Date),
  Ship.Date = mdy(Ship.Date)
)

# I make a loop to automatically turn a factor into character if it has more than 20 levels
for (col in colnames(ecom)) {
  # Check if the column is a factor
  if (is.factor(ecom[[col]])) {
    # Check if the number of levels is more 20
    if (nlevels(ecom[[col]]) > 20) {
      # Convert the factor column to character
      ecom <- mutate(ecom, !!col := as.character(!!sym(col)))
    }
  }
}

# Order data rows based on Order.Date
ecom <- arrange(ecom, Order.Date)

available_years <- unique(mutate(ecom, Order.Year = year(Order.Date))$Order.Year)


```

```{r}
plot_data <- ecom %>%
      mutate(Order.Year = year(Order.Date)) %>% 
      group_by(Segment, Order.Year) %>%
      summarise(total_order = n()) %>% 
      ungroup() %>%
      mutate(tooltip = glue("{total_order} orders"))
    
    selected_year <- 2017
    
    filtered_plot_data <- plot_data %>%
      filter(Order.Year == selected_year)
    
plot_customer_segmentation <- plot_ly(filtered_plot_data, type = "pie", labels = ~Segment,
                                      values = ~total_order, text = ~paste(Segment), hoverinfo = "value") %>%
  layout(
    title = "Segment Distribution",
    showlegend = FALSE,
    hovermode = "hoverinfo"
  )

plot_customer_segmentation









levels(ecom$Country)

```

```{r}
selected_year <- 2015
plot_data <- ecom %>% 
      filter(Order.Year == selected_year) %>% 
      group_by(Product.Name, Category, Sub.Category, Order.Year) %>% 
      summarise(total_sales = sum(Sales)) %>% 
      ungroup() %>% 
      arrange(desc(total_sales)) %>% 
      head(10) %>% 
      mutate(
        tooltip = glue("{Product.Name}\nCategory: {Sub.Category} in {Category}\nTotal ${total_sales} sales")
      )
    
    filtered_plot_data <- filter(plot_data, Order.Year == selected_year)
  
    
    plot_top10_product <- ggplot(filtered_plot_data, aes(y = reorder(Product.Name, total_sales), x = total_sales, text = tooltip)) +
      geom_bar(stat = "identity", size = 2, aes(fill = total_sales)) +
      scale_fill_gradient(low = "navy", high = "lightblue") +
      labs(
        title = "Top 10 Products by Sales"
      ) +
      theme_minimal()
    
    ggplotly(plot_top10_product, tooltip = "text")
```

```{r}
    plot_data <- ecom %>%
      group_by(Order.Year, Segment, Order.Month) %>%
      summarise(total_profit = sum(Profit)) %>% 
      ungroup() %>%
      mutate(Month.Name = month.name[Order.Month],
             tooltip = paste(Segment,
                             "\n$", Month.Name,
                             "\n$", format(round(total_profit, 2), big.mark = ","),
                             sep = ""))
    
    max_profit <- max(plot_data$total_profit)
    min_profit <- min(plot_data$total_profit)
    
    selected_year <- 2014
    
    filtered_plot_data <- plot_data %>% 
      filter(Order.Year == selected_year) %>% 
      mutate(avg_profit = median(total_profit))
    
    plot_profit_segment_trend <- ggplot(filtered_plot_data, aes(x = Order.Month, y = total_profit, text = tooltip)) +
      geom_line(aes(y = avg_profit, text = paste("Median:\n$", format(round(avg_profit, 2), big.mark = ","), sep = " ")),
                size = 1,
                col = "pink",
                group = 1,
                show.legend = TRUE) +
      geom_line(data = filter(filtered_plot_data, Segment == "Consumer"), aes(y = total_profit),
                size = 1,
                col = "green",
                group = 2,
                show.legend = TRUE) +
      geom_line(data = filter(filtered_plot_data, Segment == "Corporate"), aes(y = total_profit),
                size = 1,
                col = "red",
                group = 3,
                show.legend = TRUE) +
      geom_line(data = filter(filtered_plot_data, Segment == "Home Office"), aes(y = total_profit),
                size = 1,
                col = "blue",
                group = 4,
                show.legend = TRUE) +
      labs(
        title = glue("Segment Trends"),
        x = NULL,
        y = NULL
      ) +
      ylim(min_profit, max_profit) +
      scale_x_continuous(breaks = seq(min(filtered_plot_data$Order.Month), max(filtered_plot_data$Order.Month), by = 2),
                         labels = function(x) month.name[x]) +
      theme_minimal() +
      theme(legend.position = "bottom")  # Move the legend to the bottom
    
    ggplotly(plot_profit_segment_trend, tooltip = "text")
    
```



